/* lib_oracle -- run a table of REAL system-library calls on a PS5 and print what came back.
 *
 * Built with the ps5-payload-sdk and sent to the console's ELF loader by run_oracle.py. The call
 * table (kCases) is generated into cases_data.h at build time, so the payload needs no input. Each
 * case calls one exported function, in order, with arguments built from the spec grammar below, and
 * prints one machine-readable line per case. The lines are measurements of the console's behaviour:
 * they are the golden values prosper's HLE is diffed against (tests/hle/test_console_oracle_replay.cpp).
 *
 * Case line (TAB separated):  id  lib  func  args  expect
 *   lib     system library to dlopen, e.g. libSceRtc.sprx, or "-" for whatever the process already has
 *   args    comma separated, up to 6; "-" for none
 *   expect  comparison flags read by the replay (this payload only needs retoff:<k>)
 *
 * Argument tokens:
 *   i:<int>            integer (decimal, 0x hex, negative ok)
 *   null               NULL pointer
 *   in:<hex>           pointer to a buffer initialised with these bytes (modified calls are reported)
 *   p32:<int> p64:<int> pointer to a 4 / 8 byte little-endian buffer holding the integer
 *   out:<N>            pointer to N bytes pre-filled with 0xAB, so untouched bytes stay visible
 *   s:<text>           pointer to a NUL-terminated string; \xHH and \\ escapes (use \x2c for a comma).
 *                      An INPUT only: its contents are never reported, so a function that writes into
 *                      a string (strtok, in-place transforms) needs an in:/out: buffer instead
 *   outptr:<k>         pointer to an 8 byte out-parameter that will hold a pointer INTO the buffer of
 *                      argument k; reported as an offset so it compares across address spaces
 *   use:<id>.<k>.<off>.<size>   integer read (size 4 or 8) from argument k of an earlier case, after it ran
 *
 * Result line (TAB separated):  R  id  status  ret  retn  a<k>=<value>...
 *   status  ok | nolib | nofunc | badspec | fault:<signal>
 *   ret     the raw 64 bit return register
 *   retn    "-" unless expect has retoff:<k>; then ptr+<off> | null | ptr:foreign relative to argument k
 *   a<k>    final contents of buffer arguments (hex); for outptr, ptr+<off> | null | untouched | foreign
 *
 * Out of scope: only integer and pointer arguments (the six SysV integer registers) and an integer
 * return are modelled, so floating point and variadic functions (printf family) cannot be measured, and
 * prosper handlers registered through the guest-ABI or typed paths cannot be replayed through HleFn.
 *
 * A fault in the called function (SIGSEGV etc.) is caught and reported; the run continues. A hang is
 * not recovered -- the driver notices the missing "# done" line.
 */
#include <dlfcn.h>
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cases_data.h" /* const char kCases[]; generated by run_oracle.py */

#define MAX_ARGS 6
#define MAX_CASES 1024
#define MAX_BUF 4096
#define SENTINEL 0xAB

typedef uint64_t (*fn6_t)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);

enum kind { K_NONE, K_INT, K_NULL, K_IN, K_OUT, K_STR, K_OUTPTR };

struct arg {
  enum kind kind;
  uint64_t value; /* the register value passed */
  uint8_t *buf;   /* backing buffer for K_IN/K_OUT/K_STR/K_OUTPTR */
  size_t len;     /* reported length of buf */
  int ref;        /* K_OUTPTR: argument whose buffer the pointer is reported relative to */
};

struct result {
  char id[64];
  struct arg args[MAX_ARGS];
};

static struct result g_results[MAX_CASES];
static int g_nres;

static void *g_handles[32];
static char g_handle_names[32][96];
static int g_nhandles;

static sigjmp_buf g_jmp;
static volatile sig_atomic_t g_sig;

static void on_fault(int sig) {
  g_sig = sig;
  siglongjmp(g_jmp, 1);
}

static int hexval(int c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

/* Returns the byte count, or (size_t)-1 on a malformed or oversized string. */
static size_t decode_hex(const char *s, uint8_t *out, size_t cap) {
  size_t n = 0;
  while (s[0] && s[1] && n < cap) {
    int hi = hexval(s[0]), lo = hexval(s[1]);
    if (hi < 0 || lo < 0) return (size_t)-1;
    out[n++] = (uint8_t)((hi << 4) | lo);
    s += 2;
  }
  return s[0] ? (size_t)-1 : n;
}

static size_t decode_text(const char *s, uint8_t *out, size_t cap) {
  size_t n = 0;
  while (*s) {
    if (n + 1 >= cap) return (size_t)-1;
    if (s[0] == '\\' && s[1] == 'x' && hexval(s[2]) >= 0 && hexval(s[3]) >= 0) {
      out[n++] = (uint8_t)((hexval(s[2]) << 4) | hexval(s[3]));
      s += 4;
    } else if (s[0] == '\\' && s[1] == '\\') {
      out[n++] = '\\';
      s += 2;
    } else {
      out[n++] = (uint8_t)*s++;
    }
  }
  out[n] = 0;
  return n;
}

static int parse_int(const char *s, uint64_t *out) {
  char *end = NULL;
  if (!*s) return -1;
  if (s[0] == '-') *out = (uint64_t)strtoll(s, &end, 0);
  else *out = (uint64_t)strtoull(s, &end, 0);
  return (end && *end == '\0') ? 0 : -1;
}

static int alloc_buf(struct arg *a, size_t len) {
  a->buf = (uint8_t *)calloc(1, len + 16);
  a->len = len;
  return a->buf ? 0 : -1;
}

static const struct result *find_result(const char *id) {
  for (int i = 0; i < g_nres; i++)
    if (strcmp(g_results[i].id, id) == 0) return &g_results[i];
  return NULL;
}

/* use:<id>.<k>.<off>.<size> */
static int resolve_use(char *spec, uint64_t *out) {
  char *parts[4];
  int n = 0;
  for (char *p = spec; n < 4; n++) {
    parts[n] = p;
    char *dot = strchr(p, '.');
    if (!dot) {
      n++;
      break;
    }
    *dot = 0;
    p = dot + 1;
  }
  if (n != 4) return -1;
  const struct result *r = find_result(parts[0]);
  uint64_t k, off, size;
  if (!r || parse_int(parts[1], &k) || parse_int(parts[2], &off) || parse_int(parts[3], &size)) return -1;
  if (k >= MAX_ARGS || !r->args[k].buf || (size != 4 && size != 8) || off + size > r->args[k].len) return -1;
  *out = 0;
  memcpy(out, r->args[k].buf + off, (size_t)size);
  return 0;
}

static int parse_arg(char *tok, struct arg *a) {
  memset(a, 0, sizeof(*a));
  if (strcmp(tok, "null") == 0) {
    a->kind = K_NULL;
    return 0;
  }
  char *colon = strchr(tok, ':');
  if (!colon) return -1;
  *colon = 0;
  const char *key = tok, *val = colon + 1;
  uint64_t v = 0;
  if (strcmp(key, "i") == 0) {
    if (parse_int(val, &v)) return -1;
    a->kind = K_INT;
    a->value = v;
    return 0;
  }
  if (strcmp(key, "in") == 0) {
    uint8_t tmp[MAX_BUF];
    size_t n = decode_hex(val, tmp, sizeof(tmp));
    if (n == (size_t)-1 || alloc_buf(a, n)) return -1;
    memcpy(a->buf, tmp, n);
    a->kind = K_IN;
    a->value = (uint64_t)(uintptr_t)a->buf;
    return 0;
  }
  if (strcmp(key, "p32") == 0 || strcmp(key, "p64") == 0) {
    size_t w = key[1] == '3' ? 4 : 8;
    if (parse_int(val, &v) || alloc_buf(a, w)) return -1;
    memcpy(a->buf, &v, w); /* little endian host */
    a->kind = K_IN;
    a->value = (uint64_t)(uintptr_t)a->buf;
    return 0;
  }
  if (strcmp(key, "out") == 0) {
    if (parse_int(val, &v) || v == 0 || v > MAX_BUF || alloc_buf(a, (size_t)v)) return -1;
    memset(a->buf, SENTINEL, a->len);
    a->kind = K_OUT;
    a->value = (uint64_t)(uintptr_t)a->buf;
    return 0;
  }
  if (strcmp(key, "s") == 0) {
    uint8_t tmp[MAX_BUF];
    size_t n = decode_text(val, tmp, sizeof(tmp));
    if (n == (size_t)-1 || alloc_buf(a, n + 1)) return -1;
    memcpy(a->buf, tmp, n + 1);
    a->len = n;
    a->kind = K_STR;
    a->value = (uint64_t)(uintptr_t)a->buf;
    return 0;
  }
  if (strcmp(key, "outptr") == 0) {
    if (parse_int(val, &v) || v >= MAX_ARGS || alloc_buf(a, 8)) return -1;
    memset(a->buf, SENTINEL, 8);
    a->kind = K_OUTPTR;
    a->ref = (int)v;
    a->value = (uint64_t)(uintptr_t)a->buf;
    return 0;
  }
  if (strcmp(key, "use") == 0) {
    char spec[160];
    if (strlen(val) >= sizeof(spec)) return -1;
    strcpy(spec, val);
    if (resolve_use(spec, &v)) return -1;
    a->kind = K_INT;
    a->value = v;
    return 0;
  }
  return -1;
}

static void *handle_for(const char *lib) {
  if (strcmp(lib, "-") == 0) return RTLD_DEFAULT;
  for (int i = 0; i < g_nhandles; i++)
    if (strcmp(g_handle_names[i], lib) == 0) return g_handles[i];
  void *h = dlopen(lib, RTLD_LAZY);
  if (h && g_nhandles < 32 && strlen(lib) < sizeof(g_handle_names[0])) {
    strcpy(g_handle_names[g_nhandles], lib);
    g_handles[g_nhandles++] = h;
  }
  return h;
}

static void print_rel(uint64_t v, const struct arg *base) {
  if (v == 0) printf("null");
  else if (base && base->buf && v >= (uint64_t)(uintptr_t)base->buf &&
           v <= (uint64_t)(uintptr_t)base->buf + base->len)
    printf("ptr+%llu", (unsigned long long)(v - (uint64_t)(uintptr_t)base->buf));
  else printf("ptr:foreign");
}

static void print_hex(const uint8_t *b, size_t n) {
  for (size_t i = 0; i < n; i++) printf("%02x", b[i]);
}

static void report(const char *id, const char *status, uint64_t ret, const char *retn,
                   const struct arg *args, int nargs) {
  printf("R\t%s\t%s\t0x%016llx\t", id, status, (unsigned long long)ret);
  if (retn) printf("%s", retn);
  else printf("-");
  for (int i = 0; i < nargs; i++) {
    const struct arg *a = &args[i];
    if (a->kind == K_IN || a->kind == K_OUT) {
      printf("\ta%d=", i);
      print_hex(a->buf, a->len);
    } else if (a->kind == K_OUTPTR) {
      printf("\ta%d=", i);
      uint64_t v;
      int untouched = 1;
      for (size_t j = 0; j < 8; j++)
        if (a->buf[j] != SENTINEL) untouched = 0;
      if (untouched) printf("untouched");
      else {
        memcpy(&v, a->buf, 8);
        print_rel(v, (a->ref < nargs) ? &args[a->ref] : NULL);
      }
    }
  }
  printf("\n");
  fflush(stdout);
}

static int g_ran;

/* Free the buffers a case allocated. */
static void release_args(struct arg *args) {
  for (int i = 0; i < MAX_ARGS; i++) {
    free(args[i].buf);
    args[i].buf = NULL;
    args[i].len = 0;
  }
}

/* A finished case with a result slot keeps its buffers (a later use:/ref: reads them; main frees them at
 * the end). Without a slot (the table is full) nothing can refer to them, so free them now. */
static void finish_case(struct result *res, struct arg *args) {
  if (res) g_nres++;
  else release_args(args);
}

static void run_case(char *line) {
  char *f[5] = {0, 0, 0, 0, 0};
  int nf = 0;
  for (char *p = line; nf < 5; nf++) {
    f[nf] = p;
    char *tab = strchr(p, '\t');
    if (!tab) {
      nf++;
      break;
    }
    *tab = 0;
    p = tab + 1;
  }
  if (nf < 4) return;
  const char *id = f[0], *lib = f[1], *func = f[2];
  const char *expect = nf > 4 ? f[4] : "";

  struct result *res = g_nres < MAX_CASES ? &g_results[g_nres] : NULL;
  struct arg local[MAX_ARGS];
  struct arg *args = res ? res->args : local;
  memset(args, 0, sizeof(local));
  if (res) {
    memset(res, 0, sizeof(*res));
    strncpy(res->id, id, sizeof(res->id) - 1);
    args = res->args;
  }

  int nargs = 0;
  if (strcmp(f[3], "-") != 0 && f[3][0]) {
    char *p = f[3];
    while (p && *p) {
      if (nargs >= MAX_ARGS) {
        report(id, "badspec", 0, NULL, args, 0);
        release_args(args);
        return;
      }
      char *comma = strchr(p, ',');
      if (comma) *comma = 0;
      if (parse_arg(p, &args[nargs])) {
        report(id, "badspec", 0, NULL, args, nargs);
        release_args(args);
        return;
      }
      nargs++;
      p = comma ? comma + 1 : NULL;
    }
  }
  /* outptr references are validated now that the argument count is known */
  for (int i = 0; i < nargs; i++)
    if (args[i].kind == K_OUTPTR && (args[i].ref >= nargs || !args[args[i].ref].buf)) {
      report(id, "badspec", 0, NULL, args, nargs);
      release_args(args);
      return;
    }

  /* retoff:<k> must name an argument that has a buffer; anything else is a bad spec, not "retoff:0". */
  int retoff = -1;
  const char *ro = strstr(expect, "retoff:");
  if (ro) {
    char *end = NULL;
    unsigned long v = strtoul(ro + 7, &end, 10);
    if (end == ro + 7 || (*end != '\0' && *end != ',') || v >= (unsigned long)nargs || !args[v].buf) {
      report(id, "badspec", 0, NULL, args, nargs);
      release_args(args);
      return;
    }
    retoff = (int)v;
  }

  void *h = handle_for(lib);
  if (!h) {
    report(id, "nolib", 0, NULL, args, nargs);
    finish_case(res, args);
    return;
  }
  void *sym = dlsym(h, func);
  if (!sym) {
    report(id, "nofunc", 0, NULL, args, nargs);
    finish_case(res, args);
    return;
  }

  uint64_t a[MAX_ARGS] = {0, 0, 0, 0, 0, 0};
  for (int i = 0; i < nargs; i++) a[i] = args[i].value;

  volatile uint64_t ret = 0;
  char status[24] = "ok";
  g_sig = 0;
  if (sigsetjmp(g_jmp, 1) == 0) {
    ret = ((fn6_t)sym)(a[0], a[1], a[2], a[3], a[4], a[5]);
  } else {
    snprintf(status, sizeof(status), "fault:%d", (int)g_sig);
  }

  char retn[48] = "-";
  if (retoff >= 0) {
    /* reuse print_rel's rule without a second printer */
    uint64_t v = ret;
    if (v == 0) strcpy(retn, "null");
    else if (v >= (uint64_t)(uintptr_t)args[retoff].buf &&
             v <= (uint64_t)(uintptr_t)args[retoff].buf + args[retoff].len)
      snprintf(retn, sizeof(retn), "ptr+%llu",
               (unsigned long long)(v - (uint64_t)(uintptr_t)args[retoff].buf));
    else strcpy(retn, "ptr:foreign");
  }
  report(id, status, ret, retn, args, nargs);
  finish_case(res, args);
  g_ran++;
}

int main(void) {
  setvbuf(stdout, NULL, _IOLBF, 0);

  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = on_fault;
  sigemptyset(&sa.sa_mask);
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
  sigaction(SIGILL, &sa, NULL);
  sigaction(SIGFPE, &sa, NULL);
  sigaction(SIGABRT, &sa, NULL);

  printf("# lib_oracle v1\n");
  const char *p = kCases;
  char line[8192];
  while (*p) {
    size_t n = strcspn(p, "\n");
    size_t c = n < sizeof(line) - 1 ? n : sizeof(line) - 1;
    memcpy(line, p, c);
    line[c] = 0;
    p += n;
    if (*p == '\n') p++;
    if (line[0] == 0 || line[0] == '#') continue;
    run_case(line);
  }
  for (int i = 0; i < g_nres; i++) release_args(g_results[i].args);
  printf("# done ran=%d\n", g_ran);
  fflush(stdout);
  return 0;
}
