#!/usr/bin/env python3
"""Generate the `agcbuild` cases file: every libSceAgc command-buffer builder, probed three ways.

A libSceAgc builder (sceAgc{Dcb,Cb,Acb}<Packet>) appends one packet to the command buffer it is handed
and returns a pointer to it. It only ENCODES its arguments, so it is safe to call on a console with
arbitrary values: it writes into the descriptor's own buffer and touches nothing else. Each builder is
called with three argument patterns whose values are easy to recognise in the emitted dwords:

    a  six distinct 32-bit values   (0x11111111, 0x22222222, ...)  where each argument lands
    b  small values                 (1, 2, 3, 4, 5)                a plausible flags / count / enum
    c  two 64-bit values            (0x1111111122222222, ...)      how an address splits into lo/hi

so the measurement recovers each builder's argument mapping by observation (the signature is not
published) and the dwords it emits for a given input. The builder is passed a `dcb:512` descriptor, which
the payload and prosper's replay both build identically (tools/console_oracle/payload/lib_oracle.c).

Excluded on purpose, each for a stated reason:
  *GetSize           measured separately (the `agc` family): a size query takes no buffer
  *Patch*, *Rewind*  they STORE through a pointer into a packet built earlier, which a probe does not have
  sceAgcCreate*, sceAgcLinkShaders, sceAgcFuseShaderHalves, sceAgcGetRegisterDefaults*, ...
                     not builders: they read caller-supplied structures, so garbage arguments would be
                     dereferenced rather than encoded

Usage:
    python3 prosper/tools/console_oracle/gen_builder_cases.py --stubs <dir with libSceAgc.c> [--check]

<dir> is the ps5-payload-sdk's generated stub directory (one libSceXxx.c per firmware library, each
listing `.global <name>` for every export). Only exported NAMES are read.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[2] / "tests" / "data" / "console_oracle"
FAMILY = "agcbuild"
LIB = "libSceAgc.sprx"
BUILDER_RE = re.compile(r"^sceAgc(Dcb|Cb|Acb)[A-Z]\w*$")
EXCLUDE_RE = re.compile(r"GetSize$|Patch|Rewind")
EXPECT = "r64,retoff:0"
# dwords in the command buffer a probe is given; the largest builder (InitializeDefaultHardwareState)
# emits a few hundred, and 1024 is the payload's ceiling for a dcb: token
DCB_DWORDS = 1024

PROBES = (
    ("a", "i:0x11111111,i:0x22222222,i:0x33333333,i:0x44444444,i:0x55555555"),
    ("b", "i:1,i:2,i:3,i:4,i:5"),
    ("c", "i:0x1111111122222222,i:0x3333333344444444,i:0,i:0,i:0"),
)

HEADER = f"""# console-oracle cases: libSceAgc command-buffer builders, GENERATED by gen_builder_cases.py (do not edit
# by hand; regenerate, then re-measure with run_oracle.py --family {FAMILY} --resume 5 --prune-unmeasured).
# Each builder is called with dcb:{DCB_DWORDS} and three argument patterns (a: distinct 32-bit values, b: small
# values, c: 64-bit values) so the emitted dwords reveal the argument mapping. Builders only encode their
# arguments into the descriptor's own buffer. id\tlib\tfunc\targs\texpect
"""


def exported_names(stub_c: str) -> list[str]:
    """Sorted unique `.global <name>` names from a genstub-generated libSceXxx.c."""
    return sorted(set(re.findall(r"\.global\s+([A-Za-z0-9_]+)", stub_c)))


def builders(names: list[str]) -> list[str]:
    return [n for n in names if BUILDER_RE.match(n) and not EXCLUDE_RE.search(n)]


def case_id(func: str, probe: str) -> str:
    return f"agcbuild_{func.removeprefix('sceAgc')}_{probe}"


def render(names: list[str]) -> str:
    lines = [HEADER.rstrip("\n")]
    for func in builders(names):
        for probe, args in PROBES:
            lines.append(
                "\t".join([case_id(func, probe), LIB, func, f"dcb:{DCB_DWORDS},{args}", EXPECT])
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--stubs", required=True, type=Path, help="directory holding libSceAgc.c")
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the cases file is not what this would generate "
        "(a pruned file is allowed to be a subset: see --prune-unmeasured)",
    )
    args = ap.parse_args(argv)
    stub = args.stubs / "libSceAgc.c"
    if not stub.is_file():
        ap.error(f"{stub} not found")
    text = render(exported_names(stub.read_text(errors="replace")))
    out = DATA_DIR / f"{FAMILY}.cases.tsv"
    if args.check:
        have = {ln.split("\t")[0] for ln in out.read_text().splitlines() if ln and ln[0] != "#"}
        want = {ln.split("\t")[0] for ln in text.splitlines() if ln and ln[0] != "#"}
        extra = sorted(have - want)
        if extra:
            print(f"cases not produced by the generator: {extra[:5]}", file=sys.stderr)
            return 1
        return 0
    out.write_text(text)
    n = sum(1 for ln in text.splitlines() if ln and ln[0] != "#")
    print(f"wrote {n} cases for {n // len(PROBES)} builders -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
