#!/usr/bin/env python3
"""Run a table of real system-library calls on a PS5 and write the measured golden file.

The cases file (tests/data/console_oracle/<family>.cases.tsv) lists calls; this tool embeds it into
the lib_oracle payload, builds the payload with the ps5-payload-sdk, sends it to the console's ELF
loader, and records what the real libraries returned as <family>.golden.tsv. prosper's replay test
(tests/hle/test_console_oracle_replay.cpp) then runs its own HLE on the same arguments and diffs.

Run it from Linux or WSL (it needs make, the SDK and a network path to the console):

    python3 prosper/tools/console_oracle/run_oracle.py --family rtc \\
        --host <console-ip> --sdk <ps5-payload-sdk-root>

A family is a bare name (rtc, libc, ...): the tool reads <family>.cases.tsv and writes
<family>.golden.tsv in tests/data/console_oracle and nowhere else.

The cases grammar and result line format are documented at the top of payload/lib_oracle.c. This
file keeps its parsing and formatting as pure functions so they are unit tested without a console
(test_run_oracle.py, beside it).
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

PAYLOAD_DIR = Path(__file__).resolve().parent / "payload"
DATA_DIR = Path(__file__).resolve().parents[2] / "tests" / "data" / "console_oracle"
ID_RE = re.compile(r"\w+", re.ASCII)
# --host and --sdk are placed in a make recipe that a shell runs, so only plain characters are accepted.
HOST_RE = re.compile(r"[A-Za-z0-9.:-]+")
SDK_RE = re.compile(r"[A-Za-z0-9_./@+-]+")
GOLDEN_MAGIC = "# console-oracle golden v1"
SPEC_COLUMNS = ("id", "lib", "func", "args", "expect")


@dataclass
class Case:
    id: str
    lib: str
    func: str
    args: str
    expect: str


@dataclass
class Output:
    results: dict[str, list[str]] = field(
        default_factory=dict
    )  # id -> [status, ret, retn, bufs...]
    done: bool = False
    ran: int | None = None


def parse_cases(text: str) -> list[Case]:
    """Parse a cases file; reject bad ids, short lines and duplicate ids so a typo cannot silently
    drop or shadow a case."""
    cases: list[Case] = []
    seen: set[str] = set()
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            raise ValueError(f"line {lineno}: expected id, lib, func, args[, expect]: {line!r}")
        cid, lib, func, args = parts[:4]
        expect = parts[4] if len(parts) > 4 else ""
        if not ID_RE.fullmatch(cid):
            raise ValueError(f"line {lineno}: bad case id {cid!r} (use A-Z a-z 0-9 _)")
        if cid in seen:
            raise ValueError(f"line {lineno}: duplicate case id {cid!r}")
        seen.add(cid)
        cases.append(Case(cid, lib, func, args, expect))
    return cases


def c_string_literal(text: str) -> str:
    """Render text as adjacent C string literals, one per source line, with TAB/quote/backslash escaped."""
    out = []
    for line in text.splitlines(keepends=True):
        esc = (
            line.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\t", "\\t")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
        )
        out.append(f'    "{esc}"')
    return "\n".join(out) if out else '    ""'


def render_cases_header(text: str) -> str:
    return (
        "/* Generated by run_oracle.py from a cases file. Do not edit. */\n"
        f"static const char kCases[] =\n{c_string_literal(text)};\n"
    )


def parse_output(text: str) -> Output:
    """Pick the payload's result lines out of everything the deploy step printed."""
    out = Output()
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if line.startswith("R\t"):
            fields = line.split("\t")
            if len(fields) >= 5:
                out.results[fields[1]] = fields[2:]
        elif line.startswith("# done"):
            out.done = True
            m = re.search(r"ran=(\d+)", line)
            out.ran = int(m.group(1)) if m else None
    return out


VOLATILE = "volatile"
RAW_RET_PLACEHOLDER = "0x0000000000000000"


def scrub_volatile(expect: str, measured: list[str]) -> list[str]:
    """Replace measured values the replay never compares with a fixed placeholder.

    A case marked `ret` or `none` does not compare its buffers, a `retoff:<k>` case compares an offset
    instead of the raw return register, and a `none` case compares nothing at all. Those buffer bytes (a
    capture-time clock reading, say), that raw pointer (a heap address in the payload process) and that
    unused return value (a per-unit calibration) are not measurements anyone uses, so they are never
    written to a committed file. `measured` is [status, ret, retn, buffers...].
    """
    flags = expect.split(",")
    status, ret, retn, *buffers = measured
    if "none" in flags or any(f.startswith("retoff:") for f in flags):
        ret = RAW_RET_PLACEHOLDER
    if "ret" in flags or "none" in flags:
        buffers = [f"{b.split('=', 1)[0]}={VOLATILE}" for b in buffers]
    return [status, ret, retn, *buffers]


def build_golden(source_name: str, cases: list[Case], output: Output, date: str) -> str:
    """One line per case: the five spec columns, then the measured result (status, ret, retn, buffers...)."""
    lines = [
        GOLDEN_MAGIC,
        f"# source: {source_name}",
        f"# captured: {date}",
        "# columns: " + "\t".join(SPEC_COLUMNS) + "\tstatus\tret\tretn\tbuffers...",
    ]
    for c in cases:
        res = output.results.get(c.id)
        measured = scrub_volatile(c.expect, res if res else ["missing", RAW_RET_PLACEHOLDER, "-"])
        lines.append("\t".join([c.id, c.lib, c.func, c.args, c.expect] + measured))
    return "\n".join(lines) + "\n"


def scrub_golden_text(text: str) -> str:
    """Apply scrub_volatile to an existing golden file; header lines pass through unchanged."""
    out = []
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            out.append(line)
            continue
        f = line.split("\t")
        if len(f) < 8:
            raise ValueError(f"short golden line: {line!r}")
        out.append("\t".join(f[:5] + scrub_volatile(f[4], f[5:])))
    return "\n".join(out) + "\n"


def parse_golden(text: str) -> list[dict]:
    rows = []
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            continue
        f = line.split("\t")
        if len(f) < 8:
            raise ValueError(f"short golden line: {line!r}")
        rows.append(
            {
                "id": f[0],
                "lib": f[1],
                "func": f[2],
                "args": f[3],
                "expect": f[4],
                "status": f[5],
                "ret": f[6],
                "retn": f[7],
                "buffers": f[8:],
            }
        )
    return rows


def golden_spec_problems(golden_text: str, cases_text: str) -> list[str]:
    """The golden copies each case's spec columns; report any drift from the cases file so an edited
    case cannot keep an old measurement."""
    want = {c.id: c for c in parse_cases(cases_text)}
    got = {r["id"]: r for r in parse_golden(golden_text)}
    problems = []
    for cid, c in want.items():
        r = got.get(cid)
        if r is None:
            problems.append(f"{cid}: in cases file, absent from golden")
            continue
        for col in ("lib", "func", "args", "expect"):
            if r[col] != getattr(c, col):
                problems.append(
                    f"{cid}: {col} differs (cases {getattr(c, col)!r} / golden {r[col]!r})"
                )
    for cid in got:
        if cid not in want:
            problems.append(f"{cid}: in golden, absent from cases file")
    return problems


def family_paths(family: str) -> tuple[Path, Path]:
    """The cases and golden files of a family.

    A family is a bare name, so the tool can only ever read and write inside DATA_DIR: there is no way to
    point it at another path. The resolved paths are checked against DATA_DIR as well, which also covers
    a symlink planted in that directory.
    """
    if not ID_RE.fullmatch(family):
        raise ValueError(f"bad family name {family!r} (use A-Z a-z 0-9 _)")
    base = DATA_DIR.resolve()
    cases = (base / f"{family}.cases.tsv").resolve()
    golden = (base / f"{family}.golden.tsv").resolve()
    for path in (cases, golden):
        if not path.is_relative_to(base):
            raise ValueError(f"{path} is outside {base}")
    return cases, golden


def check_connection_args(host: str, sdk: str) -> None:
    """Reject a --host or --sdk that is not plain text before it reaches a make recipe."""
    if not HOST_RE.fullmatch(host):
        raise SystemExit(f"--host {host!r}: only letters, digits, '.', ':' and '-' are allowed")
    if not SDK_RE.fullmatch(sdk):
        raise SystemExit(
            f"--sdk {sdk!r}: only letters, digits and '_ . / @ + -' are allowed (no spaces)"
        )


def run_on_console(cases_text: str, sdk: str, host: str, port: int, timeout: int) -> str:
    """Build the payload with embedded cases and deploy it; return everything it printed."""
    check_connection_args(host, sdk)
    with tempfile.TemporaryDirectory(prefix="console_oracle_") as tmp:
        build = Path(tmp)
        for name in ("lib_oracle.c", "Makefile"):
            shutil.copy(PAYLOAD_DIR / name, build / name)
        (build / "cases_data.h").write_text(render_cases_header(cases_text))
        env = dict(os.environ, PS5_PAYLOAD_SDK=sdk, PS5_HOST=host, PS5_PORT=str(port))
        try:
            proc = subprocess.run(
                ["make", "-C", str(build), "test"],
                env=env,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as expired:
            # A hung payload never prints its "# done" line. What it printed up to the hang is the whole
            # point of resuming, so return it instead of losing the run (the exception carries bytes even
            # when text=True was requested).
            partial = expired.stdout or ""
            return partial.decode(errors="replace") if isinstance(partial, bytes) else partial
        if proc.returncode != 0 and "R\t" not in proc.stdout:
            hint = (
                "\nIs --sdk an installed ps5-payload-sdk (it needs toolchain/prospero.mk)?"
                if "prospero.mk" in proc.stderr + proc.stdout
                else ""
            )
            raise SystemExit(
                f"build or deploy failed (rc={proc.returncode}):\n{proc.stdout}\n{proc.stderr}{hint}"
            )
        return proc.stdout


HANG = "hang"


def console_reachable(host: str, port: int, timeout: float = 5.0) -> bool:
    """Whether the console's ELF loader accepts a connection (it is not pinged: the console drops ping)."""
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def cases_to_text(cases: list[Case]) -> str:
    """The inverse of parse_cases for the five spec columns (comments are not carried)."""
    return "".join("\t".join([c.id, c.lib, c.func, c.args, c.expect]) + "\n" for c in cases)


def run_resumable(cases: list[Case], run, max_restarts: int) -> Output:
    """Run `cases` through `run(cases_text) -> printed output`, surviving a payload that dies or hangs.

    The payload prints one result line per case, in order, flushing each, so when it stops before its
    "# done" line the first case without a result is the one that was running. That case is recorded as
    `hang`, and the remaining cases are run again in a fresh payload. After `max_restarts` such stops the
    rest stay without a result (reported as missing), so a console that keeps dying cannot loop forever.
    """
    results: dict[str, list[str]] = {}
    pending = list(cases)
    restarts = 0
    done = True
    while pending:
        try:
            printed = run(cases_to_text(pending))
        except SystemExit:
            if not results:
                raise  # the very first launch failed: a real error, nothing to keep
            # The console went away part way through (a failed build or deploy after earlier launches
            # succeeded). What was measured so far is kept; the rest stay missing.
            done = False
            break
        out = parse_output(printed)
        results.update(out.results)
        missing = [c for c in pending if c.id not in out.results]
        if not missing:
            pending = []
            break
        if out.done:
            # The payload finished yet skipped cases (a malformed line it ignored): nothing to resume.
            done = False
            break
        culprit, pending = missing[0], missing[1:]
        results[culprit.id] = [HANG, RAW_RET_PLACEHOLDER, "-"]
        restarts += 1
        if restarts > max_restarts:
            done = False
            break
    return Output(results=results, done=done and not pending, ran=len(results))


def split_measured(cases: list[Case], output: Output) -> tuple[list[Case], list[tuple[Case, str]]]:
    """Cases the console ran to completion (status ok) and, separately, the rest with their status
    (hang, fault:<signal>, nofunc, nolib, badspec, or missing)."""
    ok: list[Case] = []
    rest: list[tuple[Case, str]] = []
    for c in cases:
        res = output.results.get(c.id)
        status = res[0] if res else "missing"
        if status == "ok":
            ok.append(c)
        else:
            rest.append((c, status))
    return ok, rest


def prune_cases_text(text: str, keep_ids: set[str]) -> str:
    """The cases file with every case line whose id is not in keep_ids removed; comments and blank lines
    stay, so the file keeps explaining itself."""
    out = []
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#") or line.split("\t", 1)[0] in keep_ids:
            out.append(line)
    return "\n".join(out) + "\n"


def unmeasured_text(source_name: str, rest: list[tuple[Case, str]], date: str) -> str:
    lines = [
        "# console-oracle: cases the console could not measure (not in the golden)",
        f"# source: {source_name}",
        f"# captured: {date}",
        "# columns: id\tfunc\tstatus",
    ]
    lines += [f"{c.id}\t{c.func}\t{status}" for c, status in rest]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--family",
        required=True,
        help="family name, e.g. rtc: reads <family>.cases.tsv, writes <family>.golden.tsv",
    )
    ap.add_argument(
        "--host", default=os.environ.get("PS5_HOST"), help="console address (or $PS5_HOST)"
    )
    ap.add_argument("--port", type=int, default=int(os.environ.get("PS5_PORT", "9021")))
    ap.add_argument("--sdk", default=os.environ.get("PS5_PAYLOAD_SDK"), help="installed SDK root")
    ap.add_argument("--timeout", type=int, default=180, help="seconds for build + run")
    ap.add_argument(
        "--resume",
        type=int,
        default=0,
        metavar="N",
        help="survive up to N payload deaths or hangs: the case it stopped on is recorded as `hang` and "
        "the rest run again (for a bulk probe family; default 0 = one run, stop at the first death)",
    )
    ap.add_argument(
        "--prune-unmeasured",
        action="store_true",
        help="keep only the cases the console measured (status ok) in the cases and golden files, and "
        "list the rest in <family>.unmeasured.tsv; for a generated probe family",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="only check that an existing golden matches the cases file; no console needed",
    )
    ap.add_argument(
        "--scrub",
        action="store_true",
        help="rewrite an existing golden with its uncompared volatile values replaced by "
        "placeholders; no console needed",
    )
    args = ap.parse_args(argv)

    try:
        cases_path, out_path = family_paths(args.family)
    except ValueError as err:
        ap.error(str(err))
    cases_text = cases_path.read_text()
    cases = parse_cases(cases_text)

    if args.scrub:
        out_path.write_text(scrub_golden_text(out_path.read_text()))
        print(f"scrubbed {out_path}")
        return 0

    if args.check:
        problems = golden_spec_problems(out_path.read_text(), cases_text)
        for p in problems:
            print(p, file=sys.stderr)
        return 1 if problems else 0

    if not args.host or not args.sdk:
        ap.error("--host and --sdk are required (or set PS5_HOST / PS5_PAYLOAD_SDK)")

    launches = 0

    def run(text: str) -> str:
        nonlocal launches
        # A restart must not pile another payload onto a console that has stopped answering: a failed
        # connection here ends the run and keeps what was measured.
        if launches and not console_reachable(args.host, args.port):
            raise SystemExit(f"console {args.host}:{args.port} is not answering; stopping the run")
        launches += 1
        n = sum(1 for line in text.splitlines() if line.strip())
        print(f"[oracle] launch {launches}: {n} cases", file=sys.stderr, flush=True)
        return run_on_console(text, args.sdk, args.host, args.port, args.timeout)

    if args.resume > 0:
        output = run_resumable(cases, run, args.resume)
    else:
        output = parse_output(run(cases_text))
    date = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d")

    if args.prune_unmeasured:
        ok, rest = split_measured(cases, output)
        cases_path.write_text(prune_cases_text(cases_text, {c.id for c in ok}))
        out_path.write_text(build_golden(cases_path.name, ok, output, date))
        unmeasured_path = out_path.with_name(f"{args.family}.unmeasured.tsv")
        unmeasured_path.write_text(unmeasured_text(cases_path.name, rest, date))
        print(
            f"{len(ok)}/{len(cases)} cases measured -> {out_path}; "
            f"{len(rest)} unmeasured -> {unmeasured_path}"
        )
        return 0 if output.done else 2

    missing = [c.id for c in cases if c.id not in output.results]
    out_path.write_text(build_golden(cases_path.name, cases, output, date))

    print(f"{len(cases) - len(missing)}/{len(cases)} cases measured -> {out_path}")
    if not output.done:
        print(
            "WARNING: no '# done' line: the payload stopped early (crash or hang). "
            f"First missing case: {missing[0] if missing else '?'}",
            file=sys.stderr,
        )
        return 2
    if missing:
        print(f"WARNING: no result for: {', '.join(missing)}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
