#!/usr/bin/env python3
"""Run a table of real system-library calls on a PS5 and write the measured golden file.

The cases file (tests/data/console_oracle/<family>.cases.tsv) lists calls; this tool embeds it into
the lib_oracle payload, builds the payload with the ps5-payload-sdk, sends it to the console's ELF
loader, and records what the real libraries returned as <family>.golden.tsv. prosper's replay test
(tests/hle/test_console_oracle_replay.cpp) then runs its own HLE on the same arguments and diffs.

Run it from Linux or WSL (it needs make, the SDK and a network path to the console):

    python3 prosper/tools/console_oracle/run_oracle.py \\
        --cases prosper/tests/data/console_oracle/rtc.cases.tsv \\
        --host <console-ip> --sdk <ps5-payload-sdk-root>

The cases grammar and result line format are documented at the top of payload/lib_oracle.c. This
file keeps its parsing and formatting as pure functions so they are unit tested without a console
(test_run_oracle.py, beside it).
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

PAYLOAD_DIR = Path(__file__).resolve().parent / "payload"
ID_RE = re.compile(r"^[A-Za-z0-9_]+$")
GOLDEN_MAGIC = "# console-oracle golden v1"
SPEC_COLUMNS = ("id", "lib", "func", "args", "expect")


@dataclass
class Case:
    id: str
    lib: str
    func: str
    args: str
    expect: str


@dataclass
class Output:
    results: dict[str, list[str]] = field(
        default_factory=dict
    )  # id -> [status, ret, retn, bufs...]
    done: bool = False
    ran: int | None = None


def parse_cases(text: str) -> list[Case]:
    """Parse a cases file; reject bad ids, short lines and duplicate ids so a typo cannot silently
    drop or shadow a case."""
    cases: list[Case] = []
    seen: set[str] = set()
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            raise ValueError(f"line {lineno}: expected id, lib, func, args[, expect]: {line!r}")
        cid, lib, func, args = parts[:4]
        expect = parts[4] if len(parts) > 4 else ""
        if not ID_RE.match(cid):
            raise ValueError(f"line {lineno}: bad case id {cid!r} (use A-Z a-z 0-9 _)")
        if cid in seen:
            raise ValueError(f"line {lineno}: duplicate case id {cid!r}")
        seen.add(cid)
        cases.append(Case(cid, lib, func, args, expect))
    return cases


def c_string_literal(text: str) -> str:
    """Render text as adjacent C string literals, one per source line, with TAB/quote/backslash escaped."""
    out = []
    for line in text.splitlines(keepends=True):
        esc = (
            line.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\t", "\\t")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
        )
        out.append(f'    "{esc}"')
    return "\n".join(out) if out else '    ""'


def render_cases_header(text: str) -> str:
    return (
        "/* Generated by run_oracle.py from a cases file. Do not edit. */\n"
        f"static const char kCases[] =\n{c_string_literal(text)};\n"
    )


def parse_output(text: str) -> Output:
    """Pick the payload's result lines out of everything the deploy step printed."""
    out = Output()
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if line.startswith("R\t"):
            fields = line.split("\t")
            if len(fields) >= 5:
                out.results[fields[1]] = fields[2:]
        elif line.startswith("# done"):
            out.done = True
            m = re.search(r"ran=(\d+)", line)
            out.ran = int(m.group(1)) if m else None
    return out


VOLATILE = "volatile"
RAW_RET_PLACEHOLDER = "0x0000000000000000"


def scrub_volatile(expect: str, measured: list[str]) -> list[str]:
    """Replace measured values the replay never compares with a fixed placeholder.

    A case marked `ret` or `none` does not compare its buffers, and a `retoff:<k>` case compares an
    offset instead of the raw return register. Those buffer bytes (a capture-time clock reading, say)
    and that raw pointer (a heap address in the payload process) are not measurements anyone uses, so
    they are never written to a committed file. `measured` is [status, ret, retn, buffers...].
    """
    flags = expect.split(",")
    status, ret, retn, *buffers = measured
    if any(f.startswith("retoff:") for f in flags):
        ret = RAW_RET_PLACEHOLDER
    if "ret" in flags or "none" in flags:
        buffers = [f"{b.split('=', 1)[0]}={VOLATILE}" for b in buffers]
    return [status, ret, retn, *buffers]


def build_golden(source_name: str, cases: list[Case], output: Output, date: str) -> str:
    """One line per case: the five spec columns, then the measured result (status, ret, retn, buffers...)."""
    lines = [
        GOLDEN_MAGIC,
        f"# source: {source_name}",
        f"# captured: {date}",
        "# columns: " + "\t".join(SPEC_COLUMNS) + "\tstatus\tret\tretn\tbuffers...",
    ]
    for c in cases:
        res = output.results.get(c.id)
        measured = scrub_volatile(c.expect, res if res else ["missing", RAW_RET_PLACEHOLDER, "-"])
        lines.append("\t".join([c.id, c.lib, c.func, c.args, c.expect] + measured))
    return "\n".join(lines) + "\n"


def scrub_golden_text(text: str) -> str:
    """Apply scrub_volatile to an existing golden file; header lines pass through unchanged."""
    out = []
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            out.append(line)
            continue
        f = line.split("\t")
        if len(f) < 8:
            raise ValueError(f"short golden line: {line!r}")
        out.append("\t".join(f[:5] + scrub_volatile(f[4], f[5:])))
    return "\n".join(out) + "\n"


def parse_golden(text: str) -> list[dict]:
    rows = []
    for raw in text.splitlines():
        line = raw.rstrip("\r")
        if not line.strip() or line.startswith("#"):
            continue
        f = line.split("\t")
        if len(f) < 8:
            raise ValueError(f"short golden line: {line!r}")
        rows.append(
            {
                "id": f[0],
                "lib": f[1],
                "func": f[2],
                "args": f[3],
                "expect": f[4],
                "status": f[5],
                "ret": f[6],
                "retn": f[7],
                "buffers": f[8:],
            }
        )
    return rows


def golden_spec_problems(golden_text: str, cases_text: str) -> list[str]:
    """The golden copies each case's spec columns; report any drift from the cases file so an edited
    case cannot keep an old measurement."""
    want = {c.id: c for c in parse_cases(cases_text)}
    got = {r["id"]: r for r in parse_golden(golden_text)}
    problems = []
    for cid, c in want.items():
        r = got.get(cid)
        if r is None:
            problems.append(f"{cid}: in cases file, absent from golden")
            continue
        for col in ("lib", "func", "args", "expect"):
            if r[col] != getattr(c, col):
                problems.append(
                    f"{cid}: {col} differs (cases {getattr(c, col)!r} / golden {r[col]!r})"
                )
    for cid in got:
        if cid not in want:
            problems.append(f"{cid}: in golden, absent from cases file")
    return problems


def run_on_console(cases_text: str, sdk: str, host: str, port: int, timeout: int) -> str:
    """Build the payload with embedded cases and deploy it; return everything it printed."""
    if not Path(sdk, "toolchain", "prospero.mk").exists():
        raise SystemExit(
            f"--sdk {sdk!r} is not an installed ps5-payload-sdk (no toolchain/prospero.mk)"
        )
    with tempfile.TemporaryDirectory(prefix="console_oracle_") as tmp:
        build = Path(tmp)
        for name in ("lib_oracle.c", "Makefile"):
            shutil.copy(PAYLOAD_DIR / name, build / name)
        (build / "cases_data.h").write_text(render_cases_header(cases_text))
        env = dict(os.environ, PS5_PAYLOAD_SDK=sdk, PS5_HOST=host, PS5_PORT=str(port))
        proc = subprocess.run(
            ["make", "-C", str(build), "test"],
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        if proc.returncode != 0 and "R\t" not in proc.stdout:
            raise SystemExit(
                f"build or deploy failed (rc={proc.returncode}):\n{proc.stdout}\n{proc.stderr}"
            )
        return proc.stdout


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--cases", required=True, help="<family>.cases.tsv")
    ap.add_argument(
        "--out", help="golden file to write (default: <family>.golden.tsv beside --cases)"
    )
    ap.add_argument(
        "--host", default=os.environ.get("PS5_HOST"), help="console address (or $PS5_HOST)"
    )
    ap.add_argument("--port", type=int, default=int(os.environ.get("PS5_PORT", "9021")))
    ap.add_argument("--sdk", default=os.environ.get("PS5_PAYLOAD_SDK"), help="installed SDK root")
    ap.add_argument("--timeout", type=int, default=180, help="seconds for build + run")
    ap.add_argument(
        "--check",
        action="store_true",
        help="only check that an existing golden matches the cases file; no console needed",
    )
    ap.add_argument(
        "--scrub",
        action="store_true",
        help="rewrite an existing golden with its uncompared volatile values replaced by "
        "placeholders; no console needed",
    )
    args = ap.parse_args(argv)

    cases_path = Path(args.cases)
    cases_text = cases_path.read_text()
    cases = parse_cases(cases_text)
    out_path = (
        Path(args.out)
        if args.out
        else cases_path.with_name(cases_path.name.replace(".cases.tsv", ".golden.tsv"))
    )

    if args.scrub:
        out_path.write_text(scrub_golden_text(out_path.read_text()))
        print(f"scrubbed {out_path}")
        return 0

    if args.check:
        problems = golden_spec_problems(out_path.read_text(), cases_text)
        for p in problems:
            print(p, file=sys.stderr)
        return 1 if problems else 0

    if not args.host or not args.sdk:
        ap.error("--host and --sdk are required (or set PS5_HOST / PS5_PAYLOAD_SDK)")

    printed = run_on_console(cases_text, args.sdk, args.host, args.port, args.timeout)
    output = parse_output(printed)
    missing = [c.id for c in cases if c.id not in output.results]
    date = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d")
    out_path.write_text(build_golden(cases_path.name, cases, output, date))

    print(f"{len(cases) - len(missing)}/{len(cases)} cases measured -> {out_path}")
    if not output.done:
        print(
            "WARNING: no '# done' line: the payload stopped early (crash or hang). "
            f"First missing case: {missing[0] if missing else '?'}",
            file=sys.stderr,
        )
        return 2
    if missing:
        print(f"WARNING: no result for: {', '.join(missing)}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
