set(PROSPER_GENERATED_REVISION "unknown")
set(PROSPER_GENERATED_SOURCE_IDENTITY "unknown")
set(PROSPER_GENERATED_READER_POLICY "false")
if(PROSPER_REVISION_PYTHON AND PROSPER_REVISION_WORK_TREE)
  execute_process(COMMAND "${PROSPER_REVISION_PYTHON}"
    "${PROSPER_REVISION_WORK_TREE}/prosper/tools/fragment_compile_replay/reader_policy.py"
    "${PROSPER_REVISION_WORK_TREE}"
    RESULT_VARIABLE _policy_result OUTPUT_QUIET ERROR_QUIET)
  if(_policy_result EQUAL 0)
    set(PROSPER_GENERATED_READER_POLICY "true")
  endif()
endif()

# Both ordinary clones (.git directory) and linked worktrees (.git file) have an entry at their
# root. Requiring that entry prevents Git from walking up into an unrelated ancestor when this runs
# in an exported/non-Git source directory, without relying on platform-sensitive path comparisons.
if(PROSPER_REVISION_GIT_EXECUTABLE AND PROSPER_REVISION_WORK_TREE AND
   EXISTS "${PROSPER_REVISION_WORK_TREE}/.git")
  execute_process(
    COMMAND "${PROSPER_REVISION_GIT_EXECUTABLE}" rev-parse --verify HEAD
    WORKING_DIRECTORY "${PROSPER_REVISION_WORK_TREE}"
    RESULT_VARIABLE _revision_result
    OUTPUT_VARIABLE _revision_output
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  # A Git object id contains only hexadecimal digits. Reject unexpected output before placing it in
  # generated C++ rather than trying to quote arbitrary command output safely.
  if(_revision_result EQUAL 0 AND _revision_output MATCHES "^[0-9a-fA-F]+$")
    set(PROSPER_GENERATED_REVISION "${_revision_output}")
  endif()
endif()

if(PROSPER_REVISION_WORK_TREE AND PROSPER_REVISION_CONFIG_ID)
  file(GLOB_RECURSE _source_inputs RELATIVE "${PROSPER_REVISION_WORK_TREE}"
    "${PROSPER_REVISION_WORK_TREE}/prosper/src/*.cpp"
    "${PROSPER_REVISION_WORK_TREE}/prosper/src/*.hpp"
    "${PROSPER_REVISION_WORK_TREE}/prosper/src/*.h"
    "${PROSPER_REVISION_WORK_TREE}/prosper/src/*.inc"
    "${PROSPER_REVISION_WORK_TREE}/prosper/third_party/*.h"
    "${PROSPER_REVISION_WORK_TREE}/prosper/third_party/*.hpp"
    "${PROSPER_REVISION_WORK_TREE}/prosper/third_party/*.c"
    "${PROSPER_REVISION_WORK_TREE}/prosper/third_party/*.cpp"
    "${PROSPER_REVISION_WORK_TREE}/prosper/cmake/*.cmake"
    "${PROSPER_REVISION_WORK_TREE}/prosper/cmake/build_revision.cpp.in"
    "${PROSPER_REVISION_WORK_TREE}/prosper/tools/revision/compiler_dependencies.py"
    "${PROSPER_REVISION_WORK_TREE}/prosper/tools/fragment_compile_replay/reader_policy.py"
    "${PROSPER_REVISION_WORK_TREE}/prosper/tools/fragment_compile_replay/reader_policy.json"
    "${PROSPER_REVISION_WORK_TREE}/prosper/CMakeLists.txt")
  list(SORT _source_inputs)
  set(_source_manifest "config=${PROSPER_REVISION_CONFIG_ID}|build=${PROSPER_REVISION_BUILD_CONFIG}")
  # Generated by CMake, this records resolved per-target flags/defines/ABI and tool invocations,
  # including target options declared AFTER the revision library. Only its digest is embedded.
  # Source contents below are refreshed incrementally; edits after linking cannot relabel a binary.
  set(_dependencies_result 2)
  if(PROSPER_REVISION_PYTHON AND EXISTS "${PROSPER_REVISION_COMPILE_COMMANDS}")
    execute_process(COMMAND "${PROSPER_REVISION_PYTHON}"
      "${PROSPER_REVISION_WORK_TREE}/prosper/tools/revision/compiler_dependencies.py"
      "${PROSPER_REVISION_COMPILE_COMMANDS}" "${PROSPER_REVISION_WORK_TREE}"
      "${PROSPER_REVISION_GNU_VARIADIC_REQUIRED}"
      RESULT_VARIABLE _dependencies_result OUTPUT_VARIABLE _dependencies_hash
      OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    string(APPEND _source_manifest "|dependencies=${_dependencies_hash}")
  endif()
  foreach(_relative IN LISTS _source_inputs)
    file(SHA256 "${PROSPER_REVISION_WORK_TREE}/${_relative}" _source_hash)
    string(APPEND _source_manifest "\n${_relative}=${_source_hash}")
  endforeach()
  if(_source_inputs AND _dependencies_result EQUAL 0 AND _dependencies_hash MATCHES "^[0-9a-f]+$")
    string(SHA256 PROSPER_GENERATED_SOURCE_IDENTITY "${_source_manifest}")
  endif()
endif()

# configure_file preserves the destination timestamp when its contents did not change. Therefore
# the inexpensive revision query runs before each relevant build, but compilation and relinking
# happen only after the resolved revision actually changes.
configure_file(
  "${PROSPER_REVISION_TEMPLATE}"
  "${PROSPER_REVISION_OUTPUT}"
  @ONLY
  NEWLINE_STYLE UNIX)
