// synth_prx.h — a committed generator for minimal synthetic PS5 PRX modules (#2567).
//
// WHY THIS EXISTS
// ---------------
// `link_program`'s structural behaviour — the global export table, the duplicate-export collision
// guard (#1609), the alias record (#1635) and cross-module import binding — was only ever exercised
// end-to-end by `plugin_autolink`'s dump-gated block, which needs a real game dump and therefore
// never runs in CI or for any agent without that title installed. Those are exactly the assertions
// nobody notices going stale. The behaviour under test is *structural*: it depends on the shape of a
// module's dynamic tables, not on any title's content, so it can be exercised against modules we
// synthesize ourselves.
//
// PROVENANCE (the convention #2587 asks for, applied to a generated asset)
// -----------------------------------------------------------------------
//   what it is   a minimal ET_SCE_DYNAMIC PRX: one RWX PT_LOAD, one PT_DYNAMIC, a dynamic
//                symbol/string table, RELA + JMPREL relocations, DT_INIT / DT_INIT_ARRAY.
//   used by      tests/test_loader_synth_link.cpp, tests/test_loader_synth_reject.cpp
//   generated by this header, at test time, into the per-case scratch directory. Nothing is
//                committed as a binary, so there is no opaque asset to regenerate — the "command
//                that produced it" is `synth_prx_bytes(spec)` with the spec written in the test.
//
// LEGAL HYGIENE — read before extending
// -------------------------------------
// Every byte here is written from the published ELF64 layout plus prosper's own understanding of the
// PS5 dynamic tags, the same way `tests/test_runtime_prx_load.cpp` emits its module. **No byte may
// ever be carved out of a real dump**, however small: these fixtures are committed to a public
// repository, and a dump-derived fixture would put Sony-built code in it. Synthesize, never extract.
//
// WHAT THIS CANNOT DO, and why the tests do not stop here
// ------------------------------------------------------
// A fixture the loader accepts proves only that this generator and the loader agree with each other.
// That is a weaker claim than "the loader is right", and it is the claim one is most tempted to
// overstate. Two things are therefore required of any test built on this header:
//   * negative arms — a corrupted variant the loader must REJECT, each with a control that differs by
//     the one corrupted field, so the arm can show its lever moved (see the malformation knobs below);
//   * at least one module built BY HAND, outside this generator — `tests/handmade_prx.h`. A positive
//     control drawn from the same source as the null it validates tests the discriminator, never the
//     domain: this generator emits one shape (file offset == vaddr, one PT_LOAD, one fixed table
//     order), so anything the loader gets wrong about *other* legal shapes is structurally
//     inexpressible here and would read as a clean pass.
#pragma once

#include "../src/self/module.hpp"   // PT_LOAD / PT_DYNAMIC / R_X86_64_* and the ET_SCE_* types

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace prosper_test {

// ---- the fixture's fixed internal layout (file offset == vaddr throughout) --------------------
// Regions are page-of-256 aligned so a reader can find any table by eye in a hex dump.
enum : uint64_t {
    kSynthExportCode = 0x0100,   // export bodies, 0x10 apart  (cap: 16 exports)
    kSynthDynamic    = 0x0200,   // 0x100 bytes == 16 DT entries
    kSynthSymtab     = 0x0300,   // 24 B/symbol                (cap: 32 symbols)
    kSynthStrtab     = 0x0600,   // 0x200 bytes
    kSynthRela       = 0x0800,   // the DT_RELA table          (cap: 10 entries)
    kSynthJmprel     = 0x0900,   // the DT_JMPREL table        (cap: 10 entries)
    kSynthInitArray  = 0x0a00,   // DT_INIT_ARRAY[0]
    kSynthGot        = 0x0b00,   // one 8-byte slot per import (cap: 32)
    kSynthCtor       = 0x0c00,   // what DT_INIT_ARRAY[0] is relocated to point at
    kSynthInit       = 0x0d00,   // DT_INIT
    kSynthFileSize   = 0x1000,
    // build_image aligns the PT_LOAD extent up to 16 KiB, so the mapped image is larger than the
    // file. Tests that reason about the image's end (the relocation straddle arm) need this, not
    // kSynthFileSize.
    kSynthImageSize  = 0x4000,

    kSynthMaxExports = 16,
    kSynthMaxImports = 10,
    kSynthMaxSymbols = 32,
};

// The guest address of export `i` / import GOT slot `i`, relative to the module's base.
inline uint64_t synth_export_va(size_t i) { return kSynthExportCode + (uint64_t)i * 0x10; }
inline uint64_t synth_got_va(size_t i)    { return kSynthGot + (uint64_t)i * 8; }

struct SynthModuleSpec {
    // Exported NIDs, in symbol-table order. Export `i` is defined at `synth_export_va(i)`.
    std::vector<std::string> exports;
    // Imported NIDs, in symbol-table order. Import `i`'s GOT slot is at `synth_got_va(i)` and is
    // filled by an R_X86_64_JUMP_SLOT relocation.
    std::vector<std::string> imports;
    // Emit DT_INIT / DT_INIT_ARRAY (with the RELATIVE relocation that fills the array's one entry).
    bool init = true;

    // ---- deliberate malformations. Each exists for one negative arm; the arm's control is the
    // ---- same spec with only this field at its default, so the difference is exactly one field.
    uint16_t e_machine = 0x3e;                       // 0x3e = x86-64; anything else must be rejected
    bool     omit_dynamic_phdr = false;              // no PT_DYNAMIC -> the module must be rejected
    bool     zero_value_exports = false;             // st_value == 0: defined, but NOT an export
    uint64_t relative_reloc_offset = kSynthInitArray;// where DT_INIT_ARRAY[0] is patched
    // 0 = whole file; else write only N bytes. Two different refusals, both pinned in
    // test_loader_synth_reject: cutting INSIDE the program header table removes PT_DYNAMIC, so
    // `Module::load` refuses the module; cutting LATER removes nothing the parser reads, so the
    // module parses in full and `build_image` is the only stage that can see it (#2631, fixed).
    // Before that fix the later cut was silent: a PT_LOAD whose declared p_filesz exceeded the file
    // was skipped ENTIRELY, the segment mapped all-zero, the bytes that did exist were discarded, and
    // build_image still returned true. Measured with this knob at the time: truncate_to = 0x400
    // parsed 2 symbols and yielded a 16 KiB image with 0 nonzero bytes, against a control of 79.
    uint64_t truncate_to = 0;
};

namespace detail {
// memcpy, never a type-punned store: `f` is a std::vector<uint8_t> and a uint16_t*/uint32_t* write
// through it is a strict-aliasing violation even where the alignment happens to work out.
inline void sput16(std::vector<uint8_t>& f, uint64_t off, uint16_t v) { memcpy(&f[off], &v, 2); }
inline void sput32(std::vector<uint8_t>& f, uint64_t off, uint32_t v) { memcpy(&f[off], &v, 4); }
inline void sput64(std::vector<uint8_t>& f, uint64_t off, uint64_t v) { memcpy(&f[off], &v, 8); }
}   // namespace detail

// Build the module image. Returns an empty vector with *err set when the spec overflows the fixed
// layout above — loudly, rather than silently writing one table over another, which would present as
// a loader defect.
inline std::vector<uint8_t> synth_prx_bytes(const SynthModuleSpec& spec, std::string* err = nullptr) {
    using namespace detail;
    auto fail = [&](const char* m) { if (err) *err = m; return std::vector<uint8_t>(); };
    if (spec.exports.size() > kSynthMaxExports) return fail("too many exports for the fixture layout");
    if (spec.imports.size() > kSynthMaxImports) return fail("too many imports for the fixture layout");
    if (1 + spec.exports.size() + spec.imports.size() > kSynthMaxSymbols)
        return fail("too many symbols for the fixture layout");

    std::vector<uint8_t> f(kSynthFileSize, 0);

    // --- ELF header: ET_SCE_DYNAMIC PRX, x86-64, FreeBSD ABI, program headers only ---
    memcpy(&f[0], "\x7f" "ELF", 4);
    f[4] = 2; f[5] = 1; f[6] = 1; f[7] = 9;           // ELF64, LSB, version 1, ELFOSABI_FREEBSD
    sput16(f, 0x10, prosper::ET_SCE_DYNAMIC);
    sput16(f, 0x12, spec.e_machine);
    sput32(f, 0x14, 1);                               // e_version
    sput64(f, 0x18, 0);                               // e_entry
    sput64(f, 0x20, 0x40);                            // e_phoff
    sput16(f, 0x34, 64);                              // e_ehsize
    sput16(f, 0x36, 56);                              // e_phentsize
    sput16(f, 0x38, spec.omit_dynamic_phdr ? 1 : 2);  // e_phnum
    // e_shentsize / e_shnum / e_shstrndx stay zero: a PRX has no section header table.

    auto phdr = [&](int i, uint32_t type, uint32_t flags, uint64_t off, uint64_t va,
                    uint64_t filesz, uint64_t memsz, uint64_t align) {
        const uint64_t p = 0x40 + (uint64_t)i * 56;
        sput32(f, p + 0, type);  sput32(f, p + 4, flags);
        sput64(f, p + 8, off);   sput64(f, p + 16, va); sput64(f, p + 24, va);
        sput64(f, p + 32, filesz); sput64(f, p + 40, memsz); sput64(f, p + 48, align);
    };
    phdr(0, prosper::PT_LOAD, 7, 0, 0, kSynthFileSize, kSynthFileSize, 0x4000);
    if (!spec.omit_dynamic_phdr)
        phdr(1, prosper::PT_DYNAMIC, 6, kSynthDynamic, kSynthDynamic, 0x100, 0x100, 8);

    // --- code: a bare `ret` in each body. Nothing here is executed (link_program does not run guest
    // --- code); the bytes exist so the fixture is an honest module rather than a hole.
    for (size_t i = 0; i < spec.exports.size(); i++) f[synth_export_va(i)] = 0xc3;
    f[kSynthCtor] = 0xc3;
    f[kSynthInit] = 0xc3;

    // --- dynamic string table: "\0<name>\0<name>\0..." with each name in Sony's "NID#libId#modId"
    // --- form, which is what a real module's dynsym carries.
    std::vector<uint64_t> name_off;
    uint64_t so = kSynthStrtab + 1;                   // byte 0 of a strtab is the empty string
    auto add_name = [&](const std::string& nid) -> bool {
        const std::string raw = nid + "#A#A";
        if (so + raw.size() + 1 > kSynthRela) return false;
        name_off.push_back(so - kSynthStrtab);
        memcpy(&f[so], raw.data(), raw.size());
        so += raw.size() + 1;
        return true;
    };
    for (const auto& nid : spec.exports) if (!add_name(nid)) return fail("strtab overflow");
    for (const auto& nid : spec.imports) if (!add_name(nid)) return fail("strtab overflow");
    const uint64_t strsz = so - kSynthStrtab;

    // --- dynamic symbol table. Index 0 is the null symbol and is never an export.
    auto sym = [&](size_t i, uint64_t off, uint16_t shndx, uint64_t value) {
        const uint64_t p = kSynthSymtab + (uint64_t)i * 24;
        sput32(f, p + 0, (uint32_t)off);
        f[p + 4] = 0x12;                              // STB_GLOBAL | STT_FUNC
        sput16(f, p + 6, shndx);
        sput64(f, p + 8, value);
        sput64(f, p + 16, 8);                         // st_size
    };
    memset(&f[kSynthSymtab], 0, 24);
    size_t si = 1;
    for (size_t i = 0; i < spec.exports.size(); i++, si++)
        // shndx 1 (defined) with a nonzero value is what makes this an export. With
        // zero_value_exports the symbol stays *defined* but valueless, which is neither an export
        // (linker.cpp's is_exported_symbol) nor an import (module.cpp needs shndx 0 as well).
        sym(si, name_off[i], 1, spec.zero_value_exports ? 0 : synth_export_va(i));
    const size_t first_import_sym = si;
    for (size_t i = 0; i < spec.imports.size(); i++, si++)
        sym(si, name_off[spec.exports.size() + i], 0, 0);   // undefined + value 0 == a Sony import
    const uint64_t nsym = si;

    // --- relocations ---
    auto rela = [&](uint64_t at, uint64_t offset, uint32_t type, uint32_t symi, int64_t addend) {
        sput64(f, at + 0, offset);
        sput32(f, at + 8, type); sput32(f, at + 12, symi);
        sput64(f, at + 16, (uint64_t)addend);
    };
    uint64_t rela_sz = 0;
    if (spec.init) {                                  // DT_INIT_ARRAY[0] = &ctor, applied by the loader
        rela(kSynthRela, spec.relative_reloc_offset, prosper::R_X86_64_RELATIVE, 0,
             (int64_t)kSynthCtor);
        rela_sz = 24;
    }
    for (size_t i = 0; i < spec.imports.size(); i++)
        rela(kSynthJmprel + (uint64_t)i * 24, synth_got_va(i), prosper::R_X86_64_JUMP_SLOT,
             (uint32_t)(first_import_sym + i), 0);
    const uint64_t jmprel_sz = (uint64_t)spec.imports.size() * 24;

    // --- dynamic tags. DT_SCE_SYMTABSZ goes FIRST so module.cpp's "is this really a PS5 .dynamic"
    // --- run check sees an SCE tag inside its 8-entry window (module.cpp: dyn_run_ok).
    uint64_t d = kSynthDynamic;
    auto dyn = [&](uint64_t tag, uint64_t val) {
        sput64(f, d, tag); sput64(f, d + 8, val); d += 16;
    };
    dyn(0x6100003f, nsym * 24);        // DT_SCE_SYMTABSZ
    dyn(6,    kSynthSymtab);           // DT_SYMTAB
    dyn(0xb,  24);                     // DT_SYMENT
    dyn(5,    kSynthStrtab);           // DT_STRTAB
    dyn(0xa,  strsz);                  // DT_STRSZ
    dyn(7,    kSynthRela);             // DT_RELA
    dyn(8,    rela_sz);                // DT_RELASZ
    dyn(0x17, kSynthJmprel);           // DT_JMPREL
    dyn(2,    jmprel_sz);              // DT_PLTRELSZ
    if (spec.init) {
        dyn(0xc,  kSynthInit);         // DT_INIT
        dyn(0x19, kSynthInitArray);    // DT_INIT_ARRAY
        dyn(0x1b, 8);                  // DT_INIT_ARRAYSZ
    }
    dyn(0, 0);                         // DT_NULL
    if (d > kSynthDynamic + 0x100) return fail("dynamic table overflow");

    if (spec.truncate_to != 0 && spec.truncate_to < f.size())
        f.resize((size_t)spec.truncate_to);
    return f;
}

// Write the module to `path`. Returns false with *err set on any failure, so a test never proceeds
// to a content assertion against a file that was never written (which reads as a loader defect).
inline bool write_synth_prx(const std::string& path, const SynthModuleSpec& spec,
                            std::string* err = nullptr) {
    const std::vector<uint8_t> bytes = synth_prx_bytes(spec, err);
    if (bytes.empty()) return false;
    FILE* f = fopen(path.c_str(), "wb");
    if (!f) { if (err) *err = "cannot create " + path; return false; }
    const size_t n = fwrite(bytes.data(), 1, bytes.size(), f);
    fclose(f);
    if (n != bytes.size()) { if (err) *err = "short write to " + path; return false; }
    return true;
}

// Write arbitrary bytes as a module file — used for the hand-built fixtures, which are not produced
// by the generator above.
inline bool write_module_bytes(const std::string& path, const std::vector<uint8_t>& bytes,
                               std::string* err = nullptr) {
    FILE* f = fopen(path.c_str(), "wb");
    if (!f) { if (err) *err = "cannot create " + path; return false; }
    const size_t n = fwrite(bytes.data(), 1, bytes.size(), f);
    fclose(f);
    if (n != bytes.size()) { if (err) *err = "short write to " + path; return false; }
    return true;
}

}   // namespace prosper_test
