#!/usr/bin/env python3
"""Keep the architecture specification and the decision records honest, mechanically.

`prosper/docs/spec/` holds the binding architecture rules and `prosper/docs/adr/` the decisions
behind them (see each folder's AGENTS.md). Prose rules rot in a specific way: a rule names an
enforcement that was never built, a ratchet rule exists with no rule saying why, a table copied
from a constant drifts from the constant, and an accepted decision is quietly rewritten after the
fact so its history no longer says what was decided. Every check below is one of those, and each
is a property a reviewer cannot be relied on to notice.

CHECKS
  frontmatter   Every document under spec/ and adr/ (AGENTS.md excepted) opens with a frontmatter
                block whose `kind` matches its folder and whose `status` is one the kind allows.
  adr-shape     ADR files are named NNNN-slug.md, numbers are unique, and the H1 reads
                `# ADR NNNN: ...` with the same number. A superseded ADR names its successor, and
                the successor exists.
  rule-shape    A spec rule is a `### <ID> -- title` heading (ID like LAY-3 or PERF-P1). IDs are
                unique across spec/. Each rule carries a `Status:` line (accepted, or proposed
                with the ADR that proposes it) and an `Enforcement:` line.
  enforcement   `Enforcement:` tokens are drawn from a fixed vocabulary, and each resolves:
                `ratchet:<rule>` must be a rule in check_arch_ratchet.RULES, `adr:NNNN` an
                existing ADR. `review` is allowed but must say why the rule is not mechanical.
  coverage      Every check_arch_ratchet rule is cited by at least one spec rule. A ratchet that
                no rule explains is a count nobody can justify lowering or raising.
  layer-table   The table between the gen:layer-order markers in spec/layers.md equals the table
                generated from check_arch_ratchet.LAYER_ORDER. `--write` regenerates it.
  adr-immutable With --base REV: an ADR whose base copy is `accepted` may change only its
                `status` and `superseded-by` frontmatter lines, and may not be deleted. A changed
                decision is a new ADR that supersedes the old one.

WHAT IT CANNOT SEE: whether a rule is TRUE, or whether a cited enforcement actually catches what
the rule says. A `ratchet:getenv` token resolves as long as the rule exists; only a reader can tell
whether that rule is the right instrument. This gate proves the references are live, nothing more.

EXIT STATUS: 0 clean, 1 violation, 2 could not evaluate (missing folder, unreadable base). Never
read 2 as clean.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

EXIT_OK, EXIT_VIOLATION, EXIT_UNEVALUATED = 0, 1, 2

SPEC_DIR = Path("prosper/docs/spec")
ADR_DIR = Path("prosper/docs/adr")
RATCHET = Path("prosper/tools/ci/check_arch_ratchet.py")
LAYERS_DOC = SPEC_DIR / "layers.md"

KIND_STATUSES = {
    "spec": {"accepted", "draft"},
    "adr": {"proposed", "accepted", "rejected", "superseded"},
}
FOLDER_KIND = {SPEC_DIR: "spec", ADR_DIR: "adr"}
REQUIRED_KEYS = {
    "spec": ("kind", "status", "owner", "last-verified"),
    "adr": ("kind", "status", "date"),
}
ADR_MUTABLE_KEYS = ("status", "superseded-by")

RULE_HEADING_RE = re.compile(r"^###\s+([A-Z]{2,6}-[A-Z]?[0-9]+)\s+--\s+\S", re.MULTILINE)
ANY_H3_ID_RE = re.compile(r"^###\s+([A-Z]{2,6}-[A-Z]?[0-9]+)\b", re.MULTILINE)
ADR_NAME_RE = re.compile(r"^([0-9]{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
ADR_H1_RE = re.compile(r"^# ADR ([0-9]{4}): \S", re.MULTILINE)
STATUS_LINE_RE = re.compile(r"^Status:\s*(.+)$", re.MULTILINE)
ENFORCEMENT_LINE_RE = re.compile(r"^Enforcement:\s*(.+)$", re.MULTILINE)
TOKEN_RE = re.compile(r"\b(ratchet|adr|ctest|ci|review|runtime):([A-Za-z0-9_./-]*)")
GEN_BEGIN = "<!-- gen:layer-order:begin (generated by tools/docs/check_arch_docs.py --write) -->"
GEN_END = "<!-- gen:layer-order:end -->"


@dataclass(frozen=True)
class Finding:
    check: str
    path: str
    message: str

    def render(self, github: bool) -> str:
        if github:
            return f"::error file={self.path}::{self.check}: {self.message}"
        return f"{self.path}: {self.check}: {self.message}"


class EvaluationError(Exception):
    """The gate could not establish an answer; exit 2, never a pass."""


# --------------------------------------------------------------------------------------------
# Parsing
# --------------------------------------------------------------------------------------------
def split_frontmatter(text: str) -> tuple[dict[str, str] | None, str]:
    """Parse a leading `---` block of `key: value` lines. Returns (None, text) when absent.

    Deliberately a flat subset of YAML: one scalar per key, no nesting. A richer block is a
    parse error rather than a silently partial read.
    """
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return None, text
    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if not sep or not key.strip() or key != key.strip():
            raise ValueError(f"frontmatter line is not `key: value`: {line!r}")
        fields[key.strip()] = value.strip()
    return fields, text[end + 5:]


def rule_sections(body: str) -> list[tuple[str, str]]:
    """(rule id, section text) for each `### ID -- title` heading, up to the next heading."""
    heads = list(re.finditer(r"^#{1,3}\s", body, re.MULTILINE))
    out = []
    for m in RULE_HEADING_RE.finditer(body):
        nxt = next((h.start() for h in heads if h.start() > m.start()), len(body))
        out.append((m.group(1), body[m.start():nxt]))
    return out


def load_ratchet(root: Path) -> tuple[tuple[str, ...], tuple[str, ...]]:
    path = root / RATCHET
    if not path.is_file():
        raise EvaluationError(f"{RATCHET} not found under {root}")
    # Loaded from the file under --root, never from sys.modules: a cached import would answer with
    # some other tree's rules and the coverage check would compare against the wrong list.
    spec = importlib.util.spec_from_file_location(f"_ratchet_{abs(hash(str(path)))}", path)
    if spec is None or spec.loader is None:
        raise EvaluationError(f"cannot load {RATCHET}")
    mod = importlib.util.module_from_spec(spec)
    # Registered while it executes: dataclasses resolve their module through sys.modules.
    sys.modules[spec.name] = mod
    try:
        spec.loader.exec_module(mod)
        return tuple(mod.RULES), tuple(mod.LAYER_ORDER)
    except (AttributeError, SyntaxError, ImportError) as exc:
        raise EvaluationError(f"{RATCHET} has no usable RULES/LAYER_ORDER: {exc}") from exc
    finally:
        sys.modules.pop(spec.name, None)


def layer_table(order: tuple[str, ...]) -> str:
    rows = ["| rank | layer | may include |", "| ---: | --- | --- |"]
    for rank, layer in enumerate(order):
        below = ", ".join(f"`{x}`" for x in order[:rank])
        rows.append(f"| {rank} | `{layer}` | {'itself and ' + below if below else 'itself only'} |")
    rows.append("| -- | `frontends/`, `tests/` | never includable from `prosper/src` |")
    return "\n".join(rows)


def render_layer_block(order: tuple[str, ...]) -> str:
    return f"{GEN_BEGIN}\n{layer_table(order)}\n{GEN_END}"


# --------------------------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------------------------
def documents(root: Path, folder: Path) -> list[Path]:
    base = root / folder
    if not base.is_dir():
        raise EvaluationError(f"{folder} does not exist under {root}")
    return sorted(p for p in base.glob("*.md") if p.name != "AGENTS.md")


def check_frontmatter(root: Path) -> tuple[list[Finding], dict[Path, tuple[dict[str, str], str]]]:
    findings: list[Finding] = []
    parsed: dict[Path, tuple[dict[str, str], str]] = {}
    for folder, kind in FOLDER_KIND.items():
        for path in documents(root, folder):
            rel = path.relative_to(root).as_posix()
            try:
                fields, body = split_frontmatter(path.read_text(encoding="utf-8"))
            except ValueError as exc:
                findings.append(Finding("frontmatter", rel, str(exc)))
                continue
            if fields is None:
                findings.append(Finding("frontmatter", rel, "no leading --- frontmatter block"))
                continue
            for key in REQUIRED_KEYS[kind]:
                if not fields.get(key):
                    findings.append(Finding("frontmatter", rel, f"missing required key `{key}`"))
            if fields.get("kind") and fields["kind"] != kind:
                findings.append(Finding("frontmatter", rel,
                                        f"kind `{fields['kind']}` in the {kind}/ folder"))
            status = fields.get("status")
            if status and status not in KIND_STATUSES[kind]:
                allowed = ", ".join(sorted(KIND_STATUSES[kind]))
                findings.append(Finding("frontmatter", rel,
                                        f"status `{status}` is not one of: {allowed}"))
            parsed[path] = (fields, body)
    return findings, parsed


def check_adrs(root: Path, parsed) -> tuple[list[Finding], set[str]]:
    findings: list[Finding] = []
    numbers: dict[str, str] = {}
    for path in documents(root, ADR_DIR):
        rel = path.relative_to(root).as_posix()
        m = ADR_NAME_RE.match(path.name)
        if not m:
            findings.append(Finding("adr-shape", rel, "file name is not NNNN-slug.md"))
            continue
        num = m.group(1)
        if num in numbers:
            findings.append(Finding("adr-shape", rel, f"ADR number {num} also used by {numbers[num]}"))
        numbers[num] = rel
        if path not in parsed:
            continue
        fields, body = parsed[path]
        h1 = ADR_H1_RE.search(body)
        if not h1:
            findings.append(Finding("adr-shape", rel, "no `# ADR NNNN: title` heading"))
        elif h1.group(1) != num:
            findings.append(Finding("adr-shape", rel,
                                    f"heading says ADR {h1.group(1)}, file name says {num}"))
    for path in documents(root, ADR_DIR):
        if path not in parsed:
            continue
        fields, _ = parsed[path]
        rel = path.relative_to(root).as_posix()
        if fields.get("status") == "superseded":
            succ = fields.get("superseded-by", "")
            if not re.fullmatch(r"[0-9]{4}", succ):
                findings.append(Finding("adr-shape", rel,
                                        "superseded ADR needs `superseded-by: NNNN`"))
            elif succ not in numbers:
                findings.append(Finding("adr-shape", rel, f"superseded-by {succ} does not exist"))
    return findings, set(numbers)


def check_rules(root: Path, parsed, adrs: set[str], ratchet_rules: tuple[str, ...]) -> list[Finding]:
    findings: list[Finding] = []
    seen: dict[str, str] = {}
    cited_ratchets: set[str] = set()
    for path in documents(root, SPEC_DIR):
        if path not in parsed:
            continue
        rel = path.relative_to(root).as_posix()
        _, body = parsed[path]
        well_formed = {m.group(1) for m in RULE_HEADING_RE.finditer(body)}
        for m in ANY_H3_ID_RE.finditer(body):
            if m.group(1) not in well_formed:
                findings.append(Finding("rule-shape", rel,
                                        f"{m.group(1)}: heading must read `### {m.group(1)} -- title`"))
        for rule_id, section in rule_sections(body):
            if rule_id in seen:
                findings.append(Finding("rule-shape", rel, f"{rule_id} also defined in {seen[rule_id]}"))
            seen[rule_id] = rel
            status = STATUS_LINE_RE.search(section)
            if not status:
                findings.append(Finding("rule-shape", rel, f"{rule_id}: no `Status:` line"))
            else:
                value = status.group(1).strip()
                if value.startswith("proposed"):
                    if not re.search(r"\badr:[0-9]{4}\b", value):
                        findings.append(Finding("rule-shape", rel,
                                                f"{rule_id}: a proposed rule names its ADR (adr:NNNN)"))
                elif value != "accepted":
                    findings.append(Finding("rule-shape", rel,
                                            f"{rule_id}: Status is `accepted` or `proposed (adr:NNNN)`"))
                for _, num in re.findall(r"\b(adr):([0-9]{4})\b", value):
                    if num not in adrs:
                        findings.append(Finding("enforcement", rel, f"{rule_id}: adr:{num} does not exist"))
            enf = ENFORCEMENT_LINE_RE.search(section)
            if not enf:
                findings.append(Finding("rule-shape", rel, f"{rule_id}: no `Enforcement:` line"))
                continue
            tokens = TOKEN_RE.findall(enf.group(1))
            if not tokens:
                findings.append(Finding("enforcement", rel,
                                        f"{rule_id}: Enforcement names no ratchet:/ci:/ctest:/runtime:/adr:/review: token"))
            for kind, arg in tokens:
                if kind == "ratchet":
                    if arg not in ratchet_rules:
                        findings.append(Finding("enforcement", rel,
                                                f"{rule_id}: ratchet:{arg} is not a check_arch_ratchet rule"))
                    cited_ratchets.add(arg)
                elif kind == "adr" and arg not in adrs:
                    findings.append(Finding("enforcement", rel, f"{rule_id}: adr:{arg} does not exist"))
                elif kind in ("ctest", "ci", "runtime") and not arg:
                    findings.append(Finding("enforcement", rel, f"{rule_id}: {kind}: needs a name"))
                elif kind == "review" and not re.search(r"review:\S*\s*\(\S", enf.group(1)):
                    findings.append(Finding("enforcement", rel,
                                            f"{rule_id}: `review` must say in parentheses why no tool can check it"))
    for rule in ratchet_rules:
        if rule not in cited_ratchets:
            findings.append(Finding("coverage", SPEC_DIR.as_posix(),
                                    f"ratchet rule `{rule}` is cited by no spec rule"))
    return findings


def check_layer_table(root: Path, order: tuple[str, ...], write: bool) -> list[Finding]:
    path = root / LAYERS_DOC
    rel = LAYERS_DOC.as_posix()
    if not path.is_file():
        return [Finding("layer-table", rel, "file missing")]
    text = path.read_text(encoding="utf-8")
    start, end = text.find(GEN_BEGIN), text.find(GEN_END)
    if start < 0 or end < start:
        return [Finding("layer-table", rel, "gen:layer-order markers missing")]
    current = text[start:end + len(GEN_END)]
    wanted = render_layer_block(order)
    if current == wanted:
        return []
    if write:
        path.write_text(text[:start] + wanted + text[end + len(GEN_END):], encoding="utf-8")
        return []
    return [Finding("layer-table", rel,
                    "table differs from LAYER_ORDER; run tools/docs/check_arch_docs.py --write")]


def git_show(root: Path, rev: str, path: str) -> str | None:
    proc = subprocess.run(["git", "-C", str(root), "show", f"{rev}:{path}"],
                          capture_output=True, text=True, encoding="utf-8")
    return proc.stdout if proc.returncode == 0 else None


def base_adr_paths(root: Path, rev: str) -> list[str]:
    proc = subprocess.run(["git", "-C", str(root), "ls-tree", "--name-only", rev,
                           ADR_DIR.as_posix() + "/"],
                          capture_output=True, text=True, encoding="utf-8")
    if proc.returncode != 0:
        raise EvaluationError(f"cannot list {ADR_DIR} at {rev}: {proc.stderr.strip()}")
    return [p for p in proc.stdout.splitlines() if p.endswith(".md") and not p.endswith("AGENTS.md")]


def immutable_view(text: str) -> str:
    """The ADR with its mutable frontmatter lines removed."""
    lines = [ln for ln in text.splitlines()
             if not any(ln.startswith(k + ":") for k in ADR_MUTABLE_KEYS)]
    return "\n".join(lines).rstrip() + "\n"


def check_immutable(root: Path, rev: str) -> list[Finding]:
    findings = []
    for rel in base_adr_paths(root, rev):
        old = git_show(root, rev, rel)
        if old is None:
            raise EvaluationError(f"cannot read {rel} at {rev}")
        try:
            fields, _ = split_frontmatter(old)
        except ValueError:
            continue
        if not fields or fields.get("status") != "accepted":
            continue
        path = root / rel
        if not path.is_file():
            findings.append(Finding("adr-immutable", rel,
                                    "an accepted ADR was deleted; supersede it instead"))
            continue
        if immutable_view(path.read_text(encoding="utf-8")) != immutable_view(old):
            findings.append(Finding("adr-immutable", rel,
                                    "an accepted ADR's text changed; only status/superseded-by may. "
                                    "Write a new ADR that supersedes it"))
    return findings


def evaluate(root: Path, base: str | None = None, write: bool = False) -> list[Finding]:
    ratchet_rules, order = load_ratchet(root)
    findings, parsed = check_frontmatter(root)
    adr_findings, adrs = check_adrs(root, parsed)
    findings += adr_findings
    findings += check_rules(root, parsed, adrs, ratchet_rules)
    findings += check_layer_table(root, order, write)
    if base:
        findings += check_immutable(root, base)
    return findings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--root", type=Path, default=Path("."), help="repository root (default: .)")
    ap.add_argument("--base", help="git revision to check accepted-ADR immutability against")
    ap.add_argument("--write", action="store_true", help="regenerate the layer table in place")
    ap.add_argument("--github", action="store_true", help="emit GitHub annotations")
    args = ap.parse_args(argv)
    try:
        findings = evaluate(args.root.resolve(), args.base, args.write)
    except EvaluationError as exc:
        print(f"check_arch_docs: could not evaluate: {exc}", file=sys.stderr)
        return EXIT_UNEVALUATED
    for f in findings:
        print(f.render(args.github))
    if findings:
        print(f"check_arch_docs: {len(findings)} finding(s)", file=sys.stderr)
        return EXIT_VIOLATION
    print("check_arch_docs: spec and ADRs consistent")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
