// handmade_prx.h — ONE fixed PRX module, laid out by hand (#2567).
//
// This is a *fixture*, not a generator. It takes no parameters and emits one module, written
// field-by-field from the published ELF64 layout and prosper's own record of the PS5 dynamic tags —
// deliberately NOT from `tests/fixtures/synth_prx.h`'s model.
//
// WHY A SECOND, HAND-BUILT MODULE EXISTS
// --------------------------------------
// `synth_prx.h` emits exactly one shape: a single PT_LOAD, file offset == vaddr everywhere, one fixed
// order of dynamic tags. Every fixture it produces therefore inherits that geometry, so a test built
// only on it can show that the loader agrees with the generator and nothing more. A positive control
// drawn from the same source as the null it validates tests the DISCRIMINATOR, never the DOMAIN:
// anything the loader gets wrong about a *different* legal shape is structurally inexpressible in
// that generator's output and would read as a clean pass.
//
// So this module is built to differ in exactly the ways that matter to the loader:
//
//   * TWO PT_LOAD segments (R|X text, R|W data) instead of one RWX — the real shape;
//   * the data segment's file offset is NOT its vaddr (0x1000 vs 0x8000), so every dynamic table
//     reached through it exercises `Module::va2foff`'s translation rather than an identity map. A
//     loader that treated a vaddr as a file offset would parse this module as garbage and is
//     indistinguishable from a correct one on any `synth_prx.h` fixture. **This one is pinned**:
//     making `va2foff` the identity function yields 6 failures, every one of them in the handmade
//     arm, with every generator arm still green;
//   * PT_DYNAMIC's own p_offset addresses the same bytes through the covering PT_LOAD, which is the
//     shape `va2foff`'s two-pass "LOAD wins" rule (#113) was written for. **This one is NOT pinned,
//     and the fixture must not be cited as regression cover for #113.** Measured (review of #2645):
//     swapping the two passes — the actual #113 regression — leaves both cases fully green, because
//     here PT_DYNAMIC's p_offset agrees with the covering PT_LOAD, so both passes return the same
//     answer. Mis-basing that p_offset to try to separate them is *also* green, because
//     `dyn_run_ok`'s recovery re-derives the offset from the containing PT_LOAD. Pinning #113 needs
//     a module where the two passes genuinely disagree AND the recovery cannot repair it; nobody has
//     built one, and this fixture is not it;
//   * a different dynamic-tag order (DT_STRTAB before DT_SYMTAB), no DT_INIT, and a symbol table
//     carrying two exports and one import.
//
// LEGAL HYGIENE: as with `synth_prx.h`, every byte is synthesized. No part of any dump appears here,
// and none may ever be pasted in — this repository is public.
//
// PROVENANCE (#2587's convention, for a generated asset)
//   what it is   a hand-laid ET_SCE_DYNAMIC PRX, 0x2000 bytes, two PT_LOADs
//   used by      tests/hle/test_loader_synth_link.cpp (accepted), tests/hle/test_loader_synth_reject.cpp
//                (one field corrupted, must be rejected)
//   generated by `handmade_prx_bytes(export_nid_a, export_nid_b, import_nid)` at test time; nothing
//                is committed as a binary.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace prosper_test {

// ---- the hand-laid map. File offsets and vaddrs deliberately diverge past the text segment. -----
enum : uint64_t {
    kHandTextOff     = 0x0000, kHandTextVa  = 0x0000, kHandTextSz = 0x1000,
    kHandDataOff     = 0x1000, kHandDataVa  = 0x8000, kHandDataSz = 0x1000,

    kHandExportAVa   = 0x0200,   // first exported body, inside the TEXT segment
    kHandExportBVa   = 0x0210,   // second exported body

    kHandDynamicVa   = 0x8000,   // DT entries          (file 0x1000)
    kHandSymtabVa    = 0x8100,   // 4 symbols           (file 0x1100)
    kHandStrtabVa    = 0x8200,   //                     (file 0x1200)
    kHandRelaVa      = 0x8300,   // one RELATIVE        (file 0x1300)
    kHandJmprelVa    = 0x8380,   // one JUMP_SLOT       (file 0x1380)
    kHandInitArrayVa = 0x8400,   // DT_INIT_ARRAY[0]    (file 0x1400)
    kHandGotVa       = 0x8500,   // the import's slot   (file 0x1500)

    kHandFileSize    = 0x2000,
    // Program-header table offsets, so a test can corrupt one named field by hand.
    kHandPhdr0Off    = 0x0040,
    kHandPhdr1Off    = 0x0078,
    kHandPhdr2Off    = 0x00b0,   // the PT_DYNAMIC program header
};

namespace handmade_detail {
inline void hput16(std::vector<uint8_t>& f, uint64_t o, uint16_t v) { memcpy(&f[o], &v, 2); }
inline void hput32(std::vector<uint8_t>& f, uint64_t o, uint32_t v) { memcpy(&f[o], &v, 4); }
inline void hput64(std::vector<uint8_t>& f, uint64_t o, uint64_t v) { memcpy(&f[o], &v, 8); }
// vaddr -> file offset for THIS module's map. Written out rather than computed generically, because
// the point of the fixture is that the two are not the same function.
inline uint64_t hfoff(uint64_t va) {
    return va >= kHandDataVa ? kHandDataOff + (va - kHandDataVa) : kHandTextOff + va;
}
}   // namespace handmade_detail

// The fixture's bytes. `export_a` / `export_b` are exported NIDs; `import_nid` is imported.
inline std::vector<uint8_t> handmade_prx_bytes(const std::string& export_a,
                                               const std::string& export_b,
                                               const std::string& import_nid) {
    using namespace handmade_detail;
    std::vector<uint8_t> f(kHandFileSize, 0);

    // ---- ELF header (ELF64, LSB, ELFOSABI_FREEBSD, ET_SCE_DYNAMIC, EM_X86_64) ----
    memcpy(&f[0], "\x7f" "ELF", 4);
    f[4] = 2;                       // EI_CLASS  = ELFCLASS64
    f[5] = 1;                       // EI_DATA   = ELFDATA2LSB
    f[6] = 1;                       // EI_VERSION
    f[7] = 9;                       // EI_OSABI  = ELFOSABI_FREEBSD
    hput16(f, 0x10, 0xfe18);        // e_type    = ET_SCE_DYNAMIC
    hput16(f, 0x12, 0x3e);          // e_machine = EM_X86_64
    hput32(f, 0x14, 1);             // e_version
    hput64(f, 0x18, 0);             // e_entry
    hput64(f, 0x20, kHandPhdr0Off); // e_phoff
    hput64(f, 0x28, 0);             // e_shoff   (no section headers)
    hput32(f, 0x30, 0);             // e_flags
    hput16(f, 0x34, 64);            // e_ehsize
    hput16(f, 0x36, 56);            // e_phentsize
    hput16(f, 0x38, 3);             // e_phnum

    // ---- program headers ----
    auto phdr = [&](uint64_t at, uint32_t type, uint32_t flags, uint64_t off, uint64_t va,
                    uint64_t sz, uint64_t align) {
        hput32(f, at + 0x00, type);
        hput32(f, at + 0x04, flags);
        hput64(f, at + 0x08, off);
        hput64(f, at + 0x10, va);
        hput64(f, at + 0x18, va);     // p_paddr
        hput64(f, at + 0x20, sz);     // p_filesz
        hput64(f, at + 0x28, sz);     // p_memsz
        hput64(f, at + 0x30, align);
    };
    phdr(kHandPhdr0Off, 1 /*PT_LOAD*/,    5 /*R|X*/, kHandTextOff, kHandTextVa, kHandTextSz, 0x4000);
    phdr(kHandPhdr1Off, 1 /*PT_LOAD*/,    6 /*R|W*/, kHandDataOff, kHandDataVa, kHandDataSz, 0x4000);
    // PT_DYNAMIC: reached through the data PT_LOAD above. p_filesz covers only the DT entries.
    // This p_offset AGREES with the covering PT_LOAD, so va2foff's two passes return the same answer
    // here and the fixture does not discriminate their order -- see the header's second bullet
    // before citing it as #113 cover.
    phdr(kHandPhdr2Off, 2 /*PT_DYNAMIC*/, 6 /*R|W*/, hfoff(kHandDynamicVa), kHandDynamicVa, 0x100, 8);

    // ---- exported bodies: a bare `ret` each ----
    f[hfoff(kHandExportAVa)] = 0xc3;
    f[hfoff(kHandExportBVa)] = 0xc3;

    // ---- dynamic string table ----
    const std::string raw_a = export_a + "#A#A";
    const std::string raw_b = export_b + "#A#A";
    const std::string raw_i = import_nid + "#A#A";
    uint64_t so = hfoff(kHandStrtabVa) + 1;          // strtab[0] is the empty string
    const uint64_t name_a = so - hfoff(kHandStrtabVa);
    memcpy(&f[so], raw_a.data(), raw_a.size()); so += raw_a.size() + 1;
    const uint64_t name_b = so - hfoff(kHandStrtabVa);
    memcpy(&f[so], raw_b.data(), raw_b.size()); so += raw_b.size() + 1;
    const uint64_t name_i = so - hfoff(kHandStrtabVa);
    memcpy(&f[so], raw_i.data(), raw_i.size()); so += raw_i.size() + 1;
    const uint64_t strsz = so - hfoff(kHandStrtabVa);

    // ---- dynamic symbol table: null, export A, export B, one undefined import ----
    auto sym = [&](uint64_t index, uint64_t name, uint16_t shndx, uint64_t value) {
        const uint64_t p = hfoff(kHandSymtabVa) + index * 24;
        hput32(f, p + 0x00, (uint32_t)name);
        f[p + 0x04] = 0x12;                 // st_info: STB_GLOBAL | STT_FUNC
        f[p + 0x05] = 0;                    // st_other
        hput16(f, p + 0x06, shndx);
        hput64(f, p + 0x08, value);
        hput64(f, p + 0x10, 8);             // st_size
    };
    sym(0, 0, 0, 0);
    sym(1, name_a, 1, kHandExportAVa);
    sym(2, name_b, 1, kHandExportBVa);
    sym(3, name_i, 0, 0);                   // undefined + value 0 == a Sony import
    const uint64_t nsym = 4;

    // ---- relocations ----
    auto rela = [&](uint64_t at, uint64_t offset, uint32_t type, uint32_t symi, int64_t addend) {
        hput64(f, at + 0x00, offset);
        hput32(f, at + 0x08, type);
        hput32(f, at + 0x0c, symi);
        hput64(f, at + 0x10, (uint64_t)addend);
    };
    rela(hfoff(kHandRelaVa),   kHandInitArrayVa, 8 /*R_X86_64_RELATIVE*/,   0, (int64_t)kHandExportAVa);
    rela(hfoff(kHandJmprelVa), kHandGotVa,       7 /*R_X86_64_JUMP_SLOT*/,  3, 0);

    // ---- dynamic tags. Order deliberately differs from synth_prx.h's; DT_SCE_SYMTABSZ still leads
    // ---- so module.cpp's 8-entry "is this a PS5 .dynamic" window sees an SCE tag.
    uint64_t d = hfoff(kHandDynamicVa);
    auto dyn = [&](uint64_t tag, uint64_t val) {
        hput64(f, d, tag); hput64(f, d + 8, val); d += 16;
    };
    dyn(0x6100003f, nsym * 24);        // DT_SCE_SYMTABSZ
    dyn(5,    kHandStrtabVa);          // DT_STRTAB      (before DT_SYMTAB, unlike the generator)
    dyn(0xa,  strsz);                  // DT_STRSZ
    dyn(6,    kHandSymtabVa);          // DT_SYMTAB
    dyn(0xb,  24);                     // DT_SYMENT
    dyn(7,    kHandRelaVa);            // DT_RELA
    dyn(8,    24);                     // DT_RELASZ
    dyn(0x17, kHandJmprelVa);          // DT_JMPREL
    dyn(2,    24);                     // DT_PLTRELSZ
    dyn(0x19, kHandInitArrayVa);       // DT_INIT_ARRAY  (no DT_INIT at all)
    dyn(0x1b, 8);                      // DT_INIT_ARRAYSZ
    dyn(0, 0);                         // DT_NULL
    return f;
}

}   // namespace prosper_test
