// Explicit Microsoft-x64 host recovery; neither CRT unwinding nor compiler jmp_buf layouts.
#include "host/fault/win_recovery.hpp"

#ifdef _WIN32
// Derived from the published Microsoft-x64 nonvolatile-register contract. These entry points
// make no calls, allocate no stack and touch only the caller-owned state. restore never returns
// through the interrupted guest/trampoline frames, whose Windows unwind descriptors do not exist.
__asm__(".text\n"
        ".p2align 4\n"
        ".globl prosper_win_recovery_save\n"
        "prosper_win_recovery_save:\n"
        "movq %rbx, 0(%rcx)\n"
        "movq %rbp, 8(%rcx)\n"
        "movq %rdi, 16(%rcx)\n"
        "movq %rsi, 24(%rcx)\n"
        "leaq 8(%rsp), %rax\n"
        "movq %rax, 32(%rcx)\n"
        "movq %r12, 40(%rcx)\n"
        "movq %r13, 48(%rcx)\n"
        "movq %r14, 56(%rcx)\n"
        "movq %r15, 64(%rcx)\n"
        "movq (%rsp), %rax\n"
        "movq %rax, 72(%rcx)\n"
        "stmxcsr 80(%rcx)\n"
        "fnstcw 84(%rcx)\n"
        "movdqu %xmm6, 96(%rcx)\n"
        "movdqu %xmm7, 112(%rcx)\n"
        "movdqu %xmm8, 128(%rcx)\n"
        "movdqu %xmm9, 144(%rcx)\n"
        "movdqu %xmm10, 160(%rcx)\n"
        "movdqu %xmm11, 176(%rcx)\n"
        "movdqu %xmm12, 192(%rcx)\n"
        "movdqu %xmm13, 208(%rcx)\n"
        "movdqu %xmm14, 224(%rcx)\n"
        "movdqu %xmm15, 240(%rcx)\n"
        "xorl %eax, %eax\n"
        "retq\n"
        ".p2align 4\n"
        ".globl prosper_win_recovery_restore\n"
        "prosper_win_recovery_restore:\n"
        "movq 72(%rcx), %rdx\n"
        "movq 0(%rcx), %rbx\n"
        "movq 8(%rcx), %rbp\n"
        "movq 16(%rcx), %rdi\n"
        "movq 24(%rcx), %rsi\n"
        "movq 40(%rcx), %r12\n"
        "movq 48(%rcx), %r13\n"
        "movq 56(%rcx), %r14\n"
        "movq 64(%rcx), %r15\n"
        "ldmxcsr 80(%rcx)\n"
        "fldcw 84(%rcx)\n"
        "movdqu 96(%rcx), %xmm6\n"
        "movdqu 112(%rcx), %xmm7\n"
        "movdqu 128(%rcx), %xmm8\n"
        "movdqu 144(%rcx), %xmm9\n"
        "movdqu 160(%rcx), %xmm10\n"
        "movdqu 176(%rcx), %xmm11\n"
        "movdqu 192(%rcx), %xmm12\n"
        "movdqu 208(%rcx), %xmm13\n"
        "movdqu 224(%rcx), %xmm14\n"
        "movdqu 240(%rcx), %xmm15\n"
        "movq 32(%rcx), %rsp\n"
        "movl $1, %eax\n"
        "jmpq *%rdx\n");
#endif
